#!/usr/bin/env python3
"""Cut the offline suite's fixtures out of real captures, and PROVE they parse
the same.

Its output is `fixtures_generated.json`, which `smoke_test.py` loads.

WHY A GENERATED FILE RATHER THAN INLINE LITERALS
------------------------------------------------
The family's rule is fixtures inline in `smoke_test.py`. Here a fixture is an
API response: one listing record is ~5 KB of JSON, and a served page is a
megabyte. Pasting those into a Python source file as string literals would
make the suite unreadable. The generated JSON sits beside it, is
regenerated by this script, and is checked by the suite for the same
properties inline fixtures would be (the binance, rakuten and polymarket
repos do the same for the same reason).

WHAT YOU NEED TO RUN IT
-----------------------
Your own captures, in `captures/` (ignored by git), named as the SOURCES
table below expects. Take them with `--dump-html`, which writes exactly the
JSON the parser was given.

WHAT IT ENFORCES
----------------
  * every fixture is CUT from a real capture, never hand-written;
  * each listing fixture parses IDENTICALLY to the untrimmed original for
    the records it keeps, every column apart from `scraped_at`;
  * each page fixture classifies identically to its untrimmed original;
  * the scrub runs BEFORE anything is embedded:
      - the visitor, device and session ids the Scraping Browser's visit was
        given (they rode along in tracking strings), and every request's
        `correlationKey`;
      - keys the parser never reads (the site's experiment and tracking
        blocks, the persuasion banners, all but the first image), since a
        fixture should carry what the checks need and nothing more;
  * a fixture that still holds a 32-hex string outside the one context the
    credential scan forgives (a photo's file name on mmtcdn.com) is refused.

Nothing personal is in these captures: a listing names businesses, and a
review summary is counts and averages, not reviews.

    python3 make_fixtures.py [captures_dir]
"""
import copy
import json
import os
import pathlib
import re
import sys
from dataclasses import asdict
from datetime import date

REPO = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / ".github"))

from product_parser import (Query, detect_page_state,  # noqa: E402
                            initial_state_listing, parse_page)
from ci_checks import HEX32, _without_site_ids  # noqa: E402

# The ids the capturing session was issued. Anonymous, but a session's, so
# they are replaced wherever they appear rather than published.
SESSION_IDS = ("624ba330-9e4b-4a3c-9537-b862e572d339",
               "c7d57a7d-6b67-49e9-8860-d17494b76f53",
               "a35f7ce2-f17d-44d1-a781-771a8f192029",
               "18611204342190505571313255507396469595")
UUID_RE = re.compile(r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b")

GOA = Query(city="CTGOI", city_code="CTGOI", country_code="IN",
            checkin=date(2026, 10, 15), checkout=date(2026, 10, 16))
DUBAI = Query(city="CTDUB", city_code="CTDUB", country_code="UNI",
              checkin=date(2026, 10, 15), checkout=date(2026, 10, 16))
LEHRA = Query(city="CTLEH", city_code="CTLEH", country_code="IN",
              checkin=date(2026, 10, 15), checkout=date(2026, 10, 16))

# name -> (capture file, query or None, records kept per section, kind)
SOURCES = {
    "search_goa_p1": ("cg_goa_p1.json", GOA, 4, "listing"),
    "search_goa_p2": ("cg_goa_p2.json", GOA, 3, "listing"),
    "search_goa_price_asc": ("cg_sort_priceasc.json", GOA, 3, "listing"),
    "search_dubai": ("cg_CTDUB.json", DUBAI, 3, "listing"),
    "search_lehra_nearby": ("cg_CTLEH.json", LEHRA, 3, "listing"),
    # The same Goa request with the front end's `expData` left out: every
    # property comes back with no `priceDetail`. Pinned so a request that
    # loses the string is caught offline.
    "search_no_expdata": ("search_no_expdata.json", GOA, 2, "listing"),
    "search_no_hotels": ("cg_bogus.json", None, None, "json"),
    "search_bad_sort": ("cg_sort_userRatingdesc.json", None, None, "json"),
    "suggest_goa": ("suggest_Goa.json", None, 3, "suggest"),
    "suggest_dubai": ("suggest_Dubai.json", None, 3, "suggest"),
    "suggest_taj_mahal": ("suggest_Taj_Mahal.json", None, 4, "suggest"),
    "suggest_nothing": ("suggest_zzqxw.json", None, None, "json"),
    "akamai_denied_www": ("a.html", None, None, "text"),
    "akamai_denied_api": ("m.json", None, None, "text"),
    "akamai_decoy": ("akamai_decoy.html", None, None, "text"),
    "chrome_error_page": ("chrome_error_page.html", None, None, "chrome_error"),
    "landing_served": ("landing_hotels.html", None, None, "served_page"),
    # A listing PAGE fetched through the Scraper API with `cdpurl`: its
    # server-rendered state, the only data that path can read.
    "ssr_listing_goa": ("ssr_listing_goa.html", GOA, 3, "ssr"),
    "cdp_extension_injection": ("hot_0.html", None, None, "extension_tags"),
}

# Response keys the parser reads; everything else in a listing is dropped.
RESPONSE_KEYS = ("hotelCount", "noMoreHotels", "personalizedSections",
                 "locationDetail", "cityLocationDetail", "sortCriteria",
                 "lastHotelId", "lastFetchedWindowInfo", "currency")
HOTEL_DROP = ("hotelPersuasions", "appDeeplink", "sharingUrl", "seoUrl")


def scrub_text(text):
    for i, sid in enumerate(SESSION_IDS):
        text = text.replace(sid, "fixture-session-%d" % (i + 1))
    return text


def trim_listing(payload, keep):
    resp = payload.get("response") or {}
    out = {k: copy.deepcopy(resp[k]) for k in RESPONSE_KEYS if k in resp}
    for sec in out.get("personalizedSections") or []:
        sec["hotels"] = (sec.get("hotels") or [])[:keep]
        for h in sec["hotels"]:
            for k in HOTEL_DROP:
                h.pop(k, None)
            if isinstance(h.get("media"), list):
                h["media"] = h["media"][:1]
            rs = h.get("reviewSummary")
            if isinstance(rs, dict):
                rs.pop("hotelRatingSummary", None)
    return {"response": out, "correlationKey": "fixture-correlation-key"}


def rows_of(payload, query):
    return [{k: v for k, v in asdict(r).items() if k != "scraped_at"}
            for r in parse_page(payload, query)]


EXTENSION_TAG_RE = re.compile(r"<script[^>]*chrome-extension://[^>]*>\s*</script>"
                              r"|<captcha-widgets[^>]*>.*?</captcha-widgets>", re.S)


def build(captures):
    out = {}
    for name, (fname, query, keep, kind) in SOURCES.items():
        raw = scrub_text((captures / fname).read_text(encoding="utf-8"))
        if kind == "listing":
            full = json.loads(raw)
            fixture = trim_listing(full, keep)
            # Identity: the kept records parse exactly as they did in the
            # untrimmed original.
            want = []
            for sec in (full.get("response") or {}).get("personalizedSections") or []:
                want.extend((sec.get("hotels") or [])[:keep])
            got_rows = rows_of(fixture, query)
            full_rows = [r for r in rows_of(full, query)
                         if r["sku"] in {str(h.get("id")) for h in want}]
            # position is per page, so compare everything but position too
            strip = lambda rs: [{k: v for k, v in r.items() if k != "position"} for r in rs]
            if strip(got_rows) != strip(full_rows):
                raise SystemExit("%s: the trimmed fixture does not parse like "
                                 "the original" % name)
            if detect_page_state(json.dumps(fixture), 200) != detect_page_state(raw, 200):
                raise SystemExit("%s: the trimmed fixture classifies differently" % name)
            value = fixture
        elif kind == "ssr":
            full = initial_state_listing(raw)
            state = trim_listing(full, keep)["response"]
            state["searchHotelsCurrency"] = full["response"].get("searchHotelsCurrency")
            state.pop("currency", None)
            value = ("<html><head></head><body><script>window.__INITIAL_STATE__ = %s"
                     "</script></body></html>" % json.dumps({"searchHotels": state}))
            strip = lambda rs: [{k: v for k, v in r.items() if k != "position"} for r in rs]
            kept = {r["sku"] for r in rows_of(initial_state_listing(value), query)}
            if not kept or strip(rows_of(initial_state_listing(value), query)) != strip(
                    [r for r in rows_of(full, query) if r["sku"] in kept]):
                raise SystemExit("%s: the cut page does not parse like the original" % name)
        elif kind == "suggest":
            value = json.loads(raw)[:keep]
        elif kind == "json":
            value = json.loads(raw)
        elif kind == "chrome_error":
            # The page is 250 KB of Chrome's own templates; what the suite
            # needs is its shape: the site's hostname as the title, the
            # page data naming the error, and no site asset.
            m = re.search(r'"errorCode"\s*:\s*"ERR_[A-Z0-9_]+"', raw)
            title = re.search(r"<title>.*?</title>", raw, re.S)
            value = ("<html dir=\"ltr\" lang=\"en\"><head>%s</head><body "
                     "id=\"t\"><div id=\"main-frame-error\" class=\"interstitial-"
                     "wrapper\"></div><script>var loadTimeData={%s};</script>"
                     "</body></html>" % (title.group(0), m.group(0)))
            if detect_page_state(value, None) != detect_page_state(raw, None):
                raise SystemExit("%s: the cut page classifies differently" % name)
        elif kind == "served_page":
            # The served page's head, then the stretch holding its first
            # five references to its own asset host (the page's first 120 KB
            # are inline styles and config with none in them).
            hits = [m.start() for m in re.finditer(r"mmtcdn\.com", raw)]
            value = raw[:4_000] + raw[hits[0] - 200:hits[4] + 200]
            if detect_page_state(value, 200) != detect_page_state(raw, 200):
                raise SystemExit("%s: the cut page classifies differently" % name)
        elif kind == "extension_tags":
            tags = EXTENSION_TAG_RE.findall(raw)
            if len(tags) < 10:
                raise SystemExit("%s: expected the extension's injected tags, "
                                 "found %d" % (name, len(tags)))
            value = "<html><head>%s</head><body></body></html>" % "".join(tags)
        else:
            value = raw
        blob = json.dumps(value)
        for line in blob.split("\\n"):
            left = HEX32.findall(_without_site_ids(line))
            if left:
                raise SystemExit("%s: a 32-hex string survived the scrub: %s"
                                 % (name, left[:3]))
        if any(sid in blob for sid in SESSION_IDS):
            raise SystemExit("%s: a session id survived the scrub" % name)
        out[name] = value
    return out


def main():
    captures = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else REPO / "captures")
    out = build(captures)
    path = REPO / "fixtures_generated.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n",
                    encoding="utf-8")
    print("wrote %s: %d fixtures, %d bytes" % (path.name, len(out),
                                               path.stat().st_size))


if __name__ == "__main__":
    main()
